### ISSUE TITLE
Python3 M-COOKIE.py

### ISSUE THREAD

**Issue by DarkSourov777** [MAHADI-143/AUTO-COOKIE#2]
Its not working bro

python3 M-COOKIE.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/AUTO-COOKIE/M-COOKIE.py", line 19, in <module>
    from COOKIES64 import main
  File "COOKIES64.py", line 3, in init COOKIES64
ModuleNotFoundError: No module named 'rich'

**Comment by MAHADI-143** [comment]
pip install rich run
